name: CineLog CI - Sprint 2

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  quality-gate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4 

      - name: Configurar JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Permissão no Gradle
        run: chmod +x ./cinelog/gradlew

      - name: Verificação de Build e Testes Automatizados
        working-directory: cinelog
        run: ./gradlew build

      - name: Configurar Node.js para validação YAML
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Validação Sintática de arquivos YAML
        run: |
          npm install -g yaml-lint
          find . -name "*.yml" -o -name "*.yaml" | xargs -I {} yamllint {}


      - name: Verificação de Arquivos Obrigatórios
        run: |
          test -f README.md || (echo "Erro: README.md não encontrado" && exit 1)
          test -d .github/workflows/ || (echo "Erro: pasta de workflows não encontrada" && exit 1)
          test -f docs/riscos.md || (echo "Erro: documento de riscos não encontrado" && exit 1)
          test -f .github/PULL_REQUEST_TEMPLATE.md || (echo "Erro: template de PR não encontrado" && exit 1)
